- name: Build Jekyll for GitHub Pages
  uses: actions/jekyll-build-pages@v1.0.7
  with:
    # Directory where the source files reside.
    source: # optional, default is ./
    # Output directory of the build. Although it can be nested inside the source, it cannot be the same as the source directory.
    destination: # optional, default is ./_site
    # Publishes posts with a future date. When set to true, the build is made with the --future option which overrides the future option that may be set in a Jekyll configuration file.
    future: # optional
    # The SHA-1 of the git commit for which the build is running. Default to GITHUB_SHA.
    build_revision: # optional, default is ${{ github.sha }}
    # Verbose output
    verbose: # optional, default is true
    # GitHub token
    token: # default is ${{ github.token }}
    
    - name: jekyll-deploy
  # You may pin to the exact commit or the version.
  # uses: DavidS/jekyll-deploy@4e59472205269cce9739ac284303e74701fd7e9d
  uses: DavidS/jekyll-deploy@1.1.1
  with:
    # Set to "true" to only build, but not deploy. This is useful for PR testing
    build-only: # optional, default is false
    
    - name: Jekyll Action
  # You may pin to the exact commit or the version.
  # uses: lemonarc/jekyll-action@2d5e5a2316cd9d4b74ad33da527d6d9be5bff8d1
  uses: lemonarc/jekyll-action@1.0.0
  
  
  - name: Jekyll Build
  # You may pin to the exact commit or the version.
  # uses: kshehadeh/jekyll-s3-action@220371747871b9aa1b635fb30a57693891e37982
  uses: kshehadeh/jekyll-s3-action@0.1
  
  - name: Jekyll Actions
  # You may pin to the exact commit or the version.
  # uses: helaili/jekyll-action@c1527523361ec3ecc54b2371ddef44826e28c0f5
  uses: helaili/jekyll-action@2.5.0
  with:
    # The GITHUB_TOKEN secret
    token: # optional
    # The Jekyll environment to build
    jekyll_env: # optional
    # The Jekyll website source directory
    jekyll_src: # optional
    # Additional Jekyll build arguments (see https://jekyllrb.com/docs/configuration/options/#build-command-options)
    jekyll_build_options: # optional
    # The Jekyll Gemfile directory
    gem_src: # optional
    # The target branch name the site gets pushed to
    target_branch: # optional
    # The relative path where the site gets pushed to
    target_path: # optional
    # Will build the Jekyll site without publishing it
    build_only: # optional
    # The directory to build your project in
    build_dir: # optional
    # Do not overwrite whatever was already published on the target branch
    keep_history: # optional
    # Commands to run prior to build and deploy. Useful for ensuring build dependencies are up to date or installing  new dependencies. For example, use `apk --update add  imagemagick` to install ImageMagick.

    pre_build_commands: # optional
    # When set override the default bundler version provided.
    bundler_version: # optional
    # Provide an author for commits by the action.  The email address is automatically set to  `[author name]@users.noreply.github.com`

    commit_author: # optional
